// Code generated by "stringer -type=Fruit"; DO NOT EDIT.

package food

import "strconv"

const _Fruit_name = "AppleOrange"

var _Fruit_index = [...]uint8{0, 5, 11}

func (i Fruit) String() string {
	if i < 0 || i >= Fruit(len(_Fruit_index)-1) {
		return "Fruit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Fruit_name[_Fruit_index[i]:_Fruit_index[i+1]]
}
